apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dbazhenov/argocd-percona-pg.git
    targetRevision: main
    path: apps 
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 